#!/usr/bin/env python3
"""Batch translate missing i18n keys."""
import json, glob, os

translations = {
    'tokenValue': {
        'af': 'Jou GitHub-token',
        'am': 'የ GitHub ቶከንህ',
        'de': 'Dein GitHub-Token',
        'es': 'Tu token de GitHub',
        'fi': 'GitHub-tunnuksesi',
        'fr': 'Ton token GitHub',
        'ga': 'Do tócáiste GitHub',
        'hak': '你個 GitHub token',
        'hu': 'A GitHub tokened',
        'id': 'Token GitHub Anda',
        'is': 'GitHub-merkið þitt',
        'it': 'Il tuo token GitHub',
        'ka': 'შენი GitHub ტოკენი',
        'ko': '당신의 GitHub 토큰',
        'lzh': '爾之 GitHub 令牌',
        'mn': 'Таны GitHub токен',
        'nan': '你个 GitHub token',
        'nl': 'Je GitHub-token',
        'no': 'GitHub-tokenet ditt',
        'pirate': "Yer GitHub token, matey",
        'pl': 'Twój token GitHub',
        'pt_BR': 'Seu token do GitHub',
        'ru': 'Ваш токен GitHub',
        'th': 'โทเค็น GitHub ของคุณ',
        'tr': 'GitHub tokeniniz',
        'vi': 'Token GitHub của bạn',
        'wuu': '侬个 GitHub token',
        'yue': '你嘅 GitHub token',
        'zh_CN': '你的 GitHub token',
        'zh_TW': '你的 GitHub token',
    },
    'tokenName': {
        'af': 'Tokennaam (bv. Persoonlik, Werk)',
        'am': 'የቶከን ስም (ለምሳሌ፡ የግል፣ ስራ)',
        'de': 'Token-Name (z.B. Persönlich, Arbeit)',
        'es': 'Nombre del token (ej. Personal, Trabajo)',
        'fi': 'Tokenin nimi (esim. Henkilökohtainen, Työ)',
        'fr': 'Nom du token (ex. Personnel, Travail)',
        'ga': "Ainm an tócáiste (m.sh. Pearsanta, Obair)",
        'hak': 'Token 名（例如 个人、工作）',
        'hu': 'Token neve (pl. Személyes, Munka)',
        'id': 'Nama token (mis. Pribadi, Kerja)',
        'is': 'Heiti merkis (t.d. Persónulegt, Vinna)',
        'it': 'Nome del token (es. Personale, Lavoro)',
        'ka': 'ტოკენის სახელი (მაგ. პირადი, სამუშაო)',
        'ko': '토큰 이름 (예: 개인, 업무)',
        'lzh': '令牌之名（如 私用、公務）',
        'mn': 'Токений нэр (жнь. Хувийн, Ажил)',
        'nan': 'Token 名（比論 個人、工作）',
        'nl': 'Tokennaam (bijv. Persoonlijk, Werk)',
        'no': 'Tokennavn (f.eks. Personlig, Jobb)',
        'pirate': "Token name (e.g. Personal, Ship's Business)",
        'pl': 'Nazwa tokenu (np. Osobisty, Praca)',
        'pt_BR': 'Nome do token (ex. Pessoal, Trabalho)',
        'ru': 'Имя токена (напр. Личный, Рабочий)',
        'th': 'ชื่อโทเค็น (เช่น ส่วนตัว, ที่ทำงาน)',
        'tr': 'Token adı (ör. Kişisel, İş)',
        'vi': 'Tên token (vd. Cá nhân, Công việc)',
        'wuu': 'Token 名字（比方 个人、工作）',
        'yue': 'Token 名（例如 個人、工作）',
        'zh_CN': 'Token 名称（例如 个人、工作）',
        'zh_TW': 'Token 名稱（例如 個人、工作）',
    },
    'stateReview': {
        'af': 'Hersien',
        'am': 'ግምገማ',
        'de': 'Prüfen',
        'es': 'Revisar',
        'fi': 'Arviointi',
        'fr': 'Revue',
        'ga': 'Athbhreithniú',
        'hak': '审查',
        'hu': 'Átnézés',
        'id': 'Tinjau',
        'is': 'Yfirfara',
        'it': 'Revisione',
        'ka': 'განხილვა',
        'ko': '리뷰',
        'lzh': '審',
        'mn': 'Хянах',
        'nan': '審查',
        'nl': 'Beoordelen',
        'no': 'Gjennomgang',
        'pirate': 'Inspect',
        'pl': 'Przegląd',
        'pt_BR': 'Revisão',
        'ru': 'Ревью',
        'th': 'รีวิว',
        'tr': 'İnceleme',
        'vi': 'Duyệt',
        'wuu': '审查',
        'yue': '審查',
        'zh_CN': '审查',
        'zh_TW': '審查',
    },
    'stateRespond': {
        'af': 'Reageer',
        'am': 'ምላሽ',
        'de': 'Antworten',
        'es': 'Responder',
        'fi': 'Vastaa',
        'fr': 'Répondre',
        'ga': 'Freagair',
        'hak': '回覆',
        'hu': 'Válasz',
        'id': 'Tanggapi',
        'is': 'Svara',
        'it': 'Rispondi',
        'ka': 'პასუხი',
        'ko': '응답',
        'lzh': '覆',
        'mn': 'Хариулах',
        'nan': '回覆',
        'nl': 'Reageren',
        'no': 'Svar',
        'pirate': 'Reply',
        'pl': 'Odpowiedz',
        'pt_BR': 'Responder',
        'ru': 'Ответить',
        'th': 'ตอบ',
        'tr': 'Yanıtla',
        'vi': 'Phản hồi',
        'wuu': '回覆',
        'yue': '回覆',
        'zh_CN': '回复',
        'zh_TW': '回覆',
    },
    'stateMerge': {
        'af': 'Saamvoeg',
        'am': 'ማዋሃድ',
        'de': 'Zusammenführen',
        'es': 'Fusionar',
        'fi': 'Yhdistä',
        'fr': 'Fusionner',
        'ga': 'Cumaisc',
        'hak': '合并',
        'hu': 'Egyesítés',
        'id': 'Gabung',
        'is': 'Sameina',
        'it': 'Unisci',
        'ka': 'გაერთიანება',
        'ko': '병합',
        'lzh': '併',
        'mn': 'Нэгтгэх',
        'nan': '合併',
        'nl': 'Samenvoegen',
        'no': 'Slå sammen',
        'pirate': 'Merge',
        'pl': 'Scal',
        'pt_BR': 'Mesclar',
        'ru': 'Слить',
        'th': 'รวม',
        'tr': 'Birleştir',
        'vi': 'Gộp',
        'wuu': '合并',
        'yue': '合併',
        'zh_CN': '合并',
        'zh_TW': '合併',
    },
    'stateMerging': {
        'af': 'Besig om saam te voeg',
        'am': 'በማዋሃድ ላይ',
        'de': 'Wird zusammengeführt',
        'es': 'Fusionando',
        'fi': 'Yhdistetään',
        'fr': 'Fusion en cours',
        'ga': 'Ag cumasc',
        'hak': '合并中',
        'hu': 'Egyesítés folyamatban',
        'id': 'Menggabung',
        'is': 'Sameinast',
        'it': 'In unione',
        'ka': 'ერთიანდება',
        'ko': '병합 중',
        'lzh': '方併',
        'mn': 'Нэгтгэж байна',
        'nan': '合併中',
        'nl': 'Bezig met samenvoegen',
        'no': 'Slår sammen',
        'pirate': "Mergin'",
        'pl': 'Scalanie',
        'pt_BR': 'Mesclando',
        'ru': 'Сливается',
        'th': 'กำลังรวม',
        'tr': 'Birleştiriliyor',
        'vi': 'Đang gộp',
        'wuu': '合并中',
        'yue': '合併緊',
        'zh_CN': '合并中',
        'zh_TW': '合併中',
    },
    'stateStuck': {
        'af': 'Vasgevang',
        'am': 'ተጣብቋል',
        'de': 'Blockiert',
        'es': 'Atascado',
        'fi': 'Jumissa',
        'fr': 'Bloqué',
        'ga': 'Stuck',
        'hak': '卡住',
        'hu': 'Elakadt',
        'id': 'Macet',
        'is': 'Fast',
        'it': 'Bloccato',
        'ka': 'გაჩერებული',
        'ko': '막힘',
        'lzh': '滯',
        'mn': 'Гацсан',
        'nan': '窒住',
        'nl': 'Vastgelopen',
        'no': 'Fastlåst',
        'pirate': "Stuck in the doldrums",
        'pl': 'Zablokowany',
        'pt_BR': 'Travado',
        'ru': 'Застряло',
        'th': 'ติดขัด',
        'tr': 'Takıldı',
        'vi': 'Bị kẹt',
        'wuu': '卡牢',
        'yue': '卡住咗',
        'zh_CN': '卡住',
        'zh_TW': '卡住',
    },
    'optMuted': {
        'af': 'Stilgemaakte Repos / Eienaars',
        'am': 'የተዘጉ Repos / ባለቤቶች',
        'de': 'Stummgeschaltete Repos / Eigentümer',
        'es': 'Repos / Propietarios silenciados',
        'fi': 'Mykistetyt repot / omistajat',
        'fr': 'Dépôts / Propriétaires masqués',
        'ga': 'Repos / Úinéirí balbhaithe',
        'hak': '静音个 Repos / 拥有者',
        'hu': 'Némított repók / tulajdonosok',
        'id': 'Repo / Pemilik yang dibisukan',
        'is': 'Þöguð Repos / Eigendur',
        'it': 'Repo / Proprietari silenziati',
        'ka': 'დადუმებული რეპოები / მფლობელები',
        'ko': '음소거된 저장소 / 소유자',
        'lzh': '已噤之庫與主',
        'mn': 'Хаасан Repo / Эзэмшигчид',
        'nan': '靜音个 Repos / 擁有者',
        'nl': 'Gedempte repos / eigenaren',
        'no': 'Dempede repoer / eiere',
        'pirate': "Muted Repos / Cap'ns",
        'pl': 'Wyciszone repozytoria / właściciele',
        'pt_BR': 'Repos / Proprietários silenciados',
        'ru': 'Скрытые репозитории / владельцы',
        'th': 'รีโพ / เจ้าของที่ปิดเสียง',
        'tr': 'Sessize alınan depolar / sahipler',
        'vi': 'Repo / Chủ sở hữu đã tắt tiếng',
        'wuu': '静音个 Repos / 拥有者',
        'yue': '靜音嘅 Repos / 擁有者',
        'zh_CN': '已静音的仓库 / 所有者',
        'zh_TW': '已靜音的倉庫 / 擁有者',
    },
    'optNotifyNewCommits': {
        'af': 'Stel in kennis wanneer PR-outeur nuwe commits stoot',
        'am': 'PR ደራሲ አዲስ commits ሲገፋ ያሳውቁ',
        'de': 'Benachrichtigen, wenn PR-Autor neue Commits pusht',
        'es': 'Notificar cuando el autor del PR suba nuevos commits',
        'fi': 'Ilmoita kun PR:n tekijä pushaa uusia committeja',
        'fr': 'Notifier quand l\'auteur du PR pousse de nouveaux commits',
        'ga': 'Fógra nuair a bhrúnn údar PR tiomáintí nua',
        'hak': 'PR 作者推新 commit 时通知',
        'hu': 'Értesítés, ha a PR szerzője új commitokat küld',
        'id': 'Beri tahu saat penulis PR mendorong commit baru',
        'is': 'Tilkynna þegar PR-höfundur ýtir nýjum commitum',
        'it': 'Notifica quando l\'autore del PR invia nuovi commit',
        'ka': 'შეტყობინება როცა PR ავტორი ახალ კომიტებს აგზავნის',
        'ko': 'PR 작성자가 새 커밋을 푸시하면 알림',
        'lzh': 'PR 著者推新 commit 時告之',
        'mn': 'PR зохиогч шинэ commit түлхэхэд мэдэгдэх',
        'nan': 'PR 作者推新 commit 時通知',
        'nl': 'Melden wanneer PR-auteur nieuwe commits pusht',
        'no': 'Varsle når PR-forfatteren pusher nye commits',
        'pirate': "Alert me when the PR scallywag pushes new commits",
        'pl': 'Powiadom, gdy autor PR wypchnie nowe commity',
        'pt_BR': 'Notificar quando o autor do PR enviar novos commits',
        'ru': 'Уведомлять, когда автор PR отправляет новые коммиты',
        'th': 'แจ้งเตือนเมื่อผู้เขียน PR พุชคอมมิตใหม่',
        'tr': 'PR yazarı yeni commit gönderdiğinde bildir',
        'vi': 'Thông báo khi tác giả PR đẩy commit mới',
        'wuu': 'PR 作者推新 commit 辰光通知',
        'yue': '當 PR 作者 push 新 commit 時通知',
        'zh_CN': '当 PR 作者推送新提交时通知',
        'zh_TW': '當 PR 作者推送新提交時通知',
    },
    'optOnlyDirectRequests': {
        'af': 'Stel slegs in kennis vir direkte hersieningsversoeke (ignoreer spanversoeke)',
        'am': 'ለቀጥታ ግምገማ ጥያቄዎች ብቻ ያሳውቁ (የቡድን ጥያቄዎችን ይተዉ)',
        'de': 'Nur bei direkten Review-Anfragen benachrichtigen (Team-Anfragen ignorieren)',
        'es': 'Solo notificar solicitudes de revisión directas (ignorar solicitudes de equipo)',
        'fi': 'Ilmoita vain suorista arviointipyynnöistä (ohita tiimipyynnöt)',
        'fr': 'Notifier uniquement les demandes de revue directes (ignorer les demandes d\'équipe)',
        'ga': 'Ná fógair ach iarratais athbhreithnithe díreacha (déan neamhaird ar iarratais foirne)',
        'hak': '只通知直接审查请求（忽略团队请求）',
        'hu': 'Csak közvetlen review kéréseknél értesítsen (csapat kérések mellőzése)',
        'id': 'Hanya beri tahu untuk permintaan tinjauan langsung (abaikan permintaan tim)',
        'is': 'Aðeins tilkynna um beinar endurskoðunarbeiðnir (hunsa hópbeiðnir)',
        'it': 'Notifica solo richieste di revisione dirette (ignora richieste del team)',
        'ka': 'შეტყობინება მხოლოდ პირდაპირი განხილვის მოთხოვნებზე (გუნდური იგნორირება)',
        'ko': '직접 리뷰 요청만 알림 (팀 요청 무시)',
        'lzh': '唯直請審時告，隊請則略',
        'mn': 'Зөвхөн шууд хянах хүсэлтэд мэдэгдэх (багийн хүсэлтийг үл тоох)',
        'nan': '干焦通知直接審查請求（略過團隊請求）',
        'nl': 'Alleen melden bij directe review-verzoeken (teamverzoeken negeren)',
        'no': 'Bare varsle ved direkte gjennomgangsforespørsler (ignorer teamforespørsler)',
        'pirate': "Only alert for direct review requests (ignore crew requests)",
        'pl': 'Powiadamiaj tylko o bezpośrednich prośbach o przegląd (ignoruj prośby zespołowe)',
        'pt_BR': 'Notificar apenas solicitações de revisão diretas (ignorar solicitações de equipe)',
        'ru': 'Уведомлять только о прямых запросах на ревью (игнорировать командные)',
        'th': 'แจ้งเตือนเฉพาะคำขอรีวิวโดยตรง (ข้ามคำขอจากทีม)',
        'tr': 'Yalnızca doğrudan inceleme isteklerinde bildir (takım isteklerini yoksay)',
        'vi': 'Chỉ thông báo yêu cầu review trực tiếp (bỏ qua yêu cầu từ nhóm)',
        'wuu': '只通知直接审查请求（忽略团队请求）',
        'yue': '淨係通知直接審查請求（略過團隊請求）',
        'zh_CN': '仅在收到直接审查请求时通知（忽略团队请求）',
        'zh_TW': '僅在收到直接審查請求時通知（忽略團隊請求）',
    },
    'optWhitelistedTeams': {
        'af': 'Toegelate spanne (stel steeds in kennis selfs met bogenoemde aangemerk):',
        'am': 'የተፈቀዱ ቡድኖች (ከላይ ቢመረጥም አሳውቅ)፡',
        'de': 'Erlaubte Teams (trotzdem benachrichtigen, auch wenn oben aktiviert):',
        'es': 'Equipos permitidos (seguir notificando aunque lo anterior esté marcado):',
        'fi': 'Sallitut tiimit (ilmoita silti, vaikka yllä oleva on valittu):',
        'fr': 'Équipes autorisées (notifier même si l\'option ci-dessus est cochée) :',
        'ga': 'Foirne ceadaithe (fógair fós fiú le thuas roghnaithe):',
        'hak': '允许个团队（就算上头勾选了也通知）：',
        'hu': 'Engedélyezett csapatok (akkor is értesít, ha a fenti be van jelölve):',
        'id': 'Tim yang diizinkan (tetap beri tahu meski opsi di atas dicentang):',
        'is': 'Leyfð teymi (tilkynna samt þótt ofangreint sé merkt):',
        'it': 'Team consentiti (notifica comunque anche con l\'opzione sopra attiva):',
        'ka': 'დაშვებული გუნდები (მაინც შეატყობინე ზემოთ მონიშვნის მიუხედავად):',
        'ko': '허용된 팀 (위 옵션이 체크되어 있어도 알림):',
        'lzh': '許可之隊（縱上已勾，仍告之）：',
        'mn': 'Зөвшөөрөгдсөн багууд (дээрх сонголттой ч мэдэгдэх):',
        'nan': '允准个团队（就算顶头有勾嘛通知）：',
        'nl': 'Toegestane teams (toch melden, ook als bovenstaande is aangevinkt):',
        'no': 'Tillatte team (varsle likevel selv om ovenfor er huket av):',
        'pirate': "Allowed crews (still holler even with above checked):",
        'pl': 'Dozwolone zespoły (powiadamiaj mimo zaznaczenia powyżej):',
        'pt_BR': 'Equipes permitidas (ainda notificar mesmo com a opção acima marcada):',
        'ru': 'Разрешённые команды (уведомлять, даже если выше отмечено):',
        'th': 'ทีมที่อนุญาต (ยังแจ้งเตือนแม้เลือกตัวเลือกข้างบน):',
        'tr': 'İzin verilen takımlar (yukarıdaki işaretli olsa bile bildir):',
        'vi': 'Nhóm được phép (vẫn thông báo dù đã chọn ở trên):',
        'wuu': '允许个团队（就算上头勾了也通知）：',
        'yue': '允許嘅團隊（就算上面剔咗都照通知）：',
        'zh_CN': '允许的团队（即使勾选了上述选项仍然通知）：',
        'zh_TW': '允許的團隊（即使勾選了上述選項仍然通知）：',
    },
    'optWhitelistedTeamsHint': {
        'af': 'Een span-slug per reël (bv. my-org/my-team)',
        'am': 'በአንድ መስመር አንድ የቡድን slug (ለምሳሌ my-org/my-team)',
        'de': 'Ein Team-Slug pro Zeile (z.B. my-org/my-team)',
        'es': 'Un slug de equipo por línea (ej. my-org/my-team)',
        'fi': 'Yksi tiimi-slug per rivi (esim. my-org/my-team)',
        'fr': 'Un slug d\'équipe par ligne (ex. my-org/my-team)',
        'ga': 'Slug foirne amháin in aghaidh an líne (m.sh. my-org/my-team)',
        'hak': '一行一只团队 slug（例如 my-org/my-team）',
        'hu': 'Egy csapat-slug soronként (pl. my-org/my-team)',
        'id': 'Satu slug tim per baris (mis. my-org/my-team)',
        'is': 'Eitt teymi-slug á línu (t.d. my-org/my-team)',
        'it': 'Uno slug del team per riga (es. my-org/my-team)',
        'ka': 'ერთი გუნდის slug თითო ხაზზე (მაგ. my-org/my-team)',
        'ko': '한 줄에 팀 slug 하나 (예: my-org/my-team)',
        'lzh': '每行一隊之 slug（如 my-org/my-team）',
        'mn': 'Мөр бүрт нэг багийн slug (жнь. my-org/my-team)',
        'nan': '一逝一个团队 slug（比論 my-org/my-team）',
        'nl': 'Eén team-slug per regel (bijv. my-org/my-team)',
        'no': 'Én team-slug per linje (f.eks. my-org/my-team)',
        'pirate': "One crew slug per line (e.g. my-org/my-team)",
        'pl': 'Jeden slug zespołu na linię (np. my-org/my-team)',
        'pt_BR': 'Um slug de equipe por linha (ex. my-org/my-team)',
        'ru': 'Один slug команды на строку (напр. my-org/my-team)',
        'th': 'หนึ่ง team slug ต่อบรรทัด (เช่น my-org/my-team)',
        'tr': 'Satır başına bir takım slug\'ı (ör. my-org/my-team)',
        'vi': 'Một slug nhóm mỗi dòng (vd. my-org/my-team)',
        'wuu': '一行一个团队 slug（比方 my-org/my-team）',
        'yue': '一行一個團隊 slug（例如 my-org/my-team）',
        'zh_CN': '每行一个团队 slug（例如 my-org/my-team）',
        'zh_TW': '每行一個團隊 slug（例如 my-org/my-team）',
    },
    'optNothingMuted': {
        'af': 'Niks is stilgemaak nie.',
        'am': 'ምንም የተዘጋ የለም።',
        'de': 'Nichts stummgeschaltet.',
        'es': 'Nada silenciado.',
        'fi': 'Mitään ei ole mykistetty.',
        'fr': 'Rien de masqué.',
        'ga': 'Rud ar bith balbhaithe.',
        'hak': '无静音个。',
        'hu': 'Semmi nincs némítva.',
        'id': 'Tidak ada yang dibisukan.',
        'is': 'Ekkert þagað.',
        'it': 'Nulla silenziato.',
        'ka': 'არაფერია დადუმებული.',
        'ko': '음소거된 항목 없음.',
        'lzh': '無所噤。',
        'mn': 'Хаасан зүйл байхгүй.',
        'nan': '無靜音个。',
        'nl': 'Niets gedempt.',
        'no': 'Ingenting dempet.',
        'pirate': "Nothin' muted, cap'n.",
        'pl': 'Nic nie jest wyciszone.',
        'pt_BR': 'Nada silenciado.',
        'ru': 'Ничего не скрыто.',
        'th': 'ไม่มีรายการที่ปิดเสียง',
        'tr': 'Sessize alınmış bir şey yok.',
        'vi': 'Chưa tắt tiếng mục nào.',
        'wuu': '呒没静音个。',
        'yue': '冇靜音嘅嘢。',
        'zh_CN': '没有已静音的内容。',
        'zh_TW': '沒有已靜音的內容。',
    },
    'optMutedDesc': {
        'af': 'Stilgemaakte repos en eienaars word van die aandag-stel en kenteken-telling verberg.',
        'am': 'የተዘጉ repos እና ባለቤቶች ከትኩረት ስብስቡ እና ባጅ ቆጠራ ተደብቀዋል።',
        'de': 'Stummgeschaltete Repos und Eigentümer werden aus dem Attention Set und der Badge-Zählung ausgeblendet.',
        'es': 'Los repos y propietarios silenciados se ocultan del conjunto de atención y del contador del badge.',
        'fi': 'Mykistetyt repot ja omistajat piilotetaan huomiojoukosta ja badge-laskurista.',
        'fr': 'Les dépôts et propriétaires masqués sont cachés de l\'attention set et du badge.',
        'ga': 'Bíonn repos agus úinéirí balbhaithe i bhfolach ón attention set agus ón gcomhaireamh suaitheantais.',
        'hak': '静音个 repos 同拥有者会从注意集合同徽章计数里头隐藏。',
        'hu': 'A némított repók és tulajdonosok el vannak rejtve az attention setből és a badge-számból.',
        'id': 'Repo dan pemilik yang dibisukan disembunyikan dari attention set dan hitungan badge.',
        'is': 'Þöguð repos og eigendur eru falin frá attention setinu og merkja-tölunni.',
        'it': 'I repo e proprietari silenziati sono nascosti dall\'attention set e dal conteggio badge.',
        'ka': 'დადუმებული რეპოები და მფლობელები დამალულია attention set-იდან და badge-ის რაოდენობიდან.',
        'ko': '음소거된 저장소와 소유자는 어텐션 셋과 배지 카운트에서 숨겨집니다.',
        'lzh': '已噤之庫與主，隱於注意集及徽數。',
        'mn': 'Хаасан repo болон эзэмшигчид анхаарлын олонлог болон badge тооноос нуугдана.',
        'nan': '静音个 repos 佮拥有者会对注意集合佮徽章计数内底隐藏。',
        'nl': 'Gedempte repos en eigenaren zijn verborgen uit de attention set en badge-telling.',
        'no': 'Dempede repoer og eiere skjules fra attention settet og badge-tellingen.',
        'pirate': "Muted repos an' owners be hidden from yer attention set an' badge count.",
        'pl': 'Wyciszone repozytoria i właściciele są ukryte z attention setu i licznika badge.',
        'pt_BR': 'Repos e proprietários silenciados ficam ocultos do attention set e da contagem do badge.',
        'ru': 'Скрытые репозитории и владельцы не отображаются в attention set и счётчике badge.',
        'th': 'รีโพและเจ้าของที่ปิดเสียงจะถูกซ่อนจาก attention set และตัวนับ badge',
        'tr': 'Sessize alınan depolar ve sahipler attention set ve badge sayısından gizlenir.',
        'vi': 'Repo và chủ sở hữu đã tắt tiếng sẽ ẩn khỏi attention set và số đếm badge.',
        'wuu': '静音个 repos 搭拥有者会从注意集合搭徽章计数里向隐藏。',
        'yue': '靜音嘅 repos 同擁有者會從 attention set 同 badge 計數入面隱藏。',
        'zh_CN': '已静音的仓库和所有者将从关注集和徽章计数中隐藏。',
        'zh_TW': '已靜音的倉庫和擁有者將從關注集和徽章計數中隱藏。',
    },
    'filterPlaceholder': {
        'af': 'Filter PRs...',
        'am': 'PRs አጣራ...',
        'de': 'PRs filtern...',
        'es': 'Filtrar PRs...',
        'fi': 'Suodata PR:t...',
        'fr': 'Filtrer les PRs...',
        'ga': 'Scag PRanna...',
        'hak': '筛选 PR...',
        'hu': 'PR-ek szűrése...',
        'id': 'Filter PR...',
        'is': 'Sía PRs...',
        'it': 'Filtra PR...',
        'ka': 'PR-ების ფილტრი...',
        'ko': 'PR 필터...',
        'lzh': '篩PR...',
        'mn': 'PR шүүх...',
        'nan': '筛选 PR...',
        'nl': 'PRs filteren...',
        'no': 'Filtrer PRer...',
        'pirate': "Filter PRs, ye scurvy dog...",
        'pl': 'Filtruj PR...',
        'pt_BR': 'Filtrar PRs...',
        'ru': 'Фильтр PR...',
        'th': 'กรอง PR...',
        'tr': "PR'leri filtrele...",
        'vi': 'Lọc PR...',
        'wuu': '筛选 PR...',
        'yue': '篩選 PR...',
        'zh_CN': '筛选 PR...',
        'zh_TW': '篩選 PR...',
    },
}

# Apply translations
os.chdir(os.path.expanduser('~/clawspace/github-attention-set'))

for locale_dir in sorted(glob.glob('_locales/*/')):
    locale = locale_dir.strip('/').split('/')[-1]
    if locale == 'en':
        continue
    
    filepath = os.path.join(locale_dir, 'messages.json')
    msgs = json.load(open(filepath))
    changed = False
    
    for key, locales in translations.items():
        if locale in locales and key in msgs:
            en_file = json.load(open('_locales/en/messages.json'))
            if msgs[key]['message'] == en_file[key]['message']:
                msgs[key]['message'] = locales[locale]
                changed = True
    
    if changed:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(msgs, f, ensure_ascii=False, indent=2)
            f.write('\n')
        print(f'Updated: {locale}')

print('Done!')
